[package]
name = "parser"
version = "0.1.0"
authors = ["Isaac Elliott <isaace71295@gmail.com>"]
edition = "2018"

[dependencies]
bit-set = "0.5.1"
ast = { path = "../ast" }
errors = { path = "../errors" }
lexer = { path = "../lexer" }
span = { path = "../span" }